tailwind.config = {
    darkMode: "class",
    theme: {
      extend: {
        colors: {
          tertiary: "#151614",
          "surface-dim": "#dbd9d9",
          error: "#ba1a1a",
          secondary: "#8e4c31",
          "secondary-fixed-dim": "#ffb599",
          "on-primary-container": "#8291ad",
          "on-error": "#ffffff",
          "on-background": "#1b1c1c",
          "inverse-primary": "#b8c7e5",
          "on-secondary-container": "#793c22",
          "tertiary-fixed": "#e5e2de",
          "secondary-fixed": "#ffdbce",
          outline: "#75777e",
          "on-surface-variant": "#44474d",
          "on-secondary-fixed": "#370e00",
          "surface-container": "#efeded",
          "primary-container": "#1b2a41",
          background: "#fbf9f8",
          "on-secondary-fixed-variant": "#71361c",
          "on-tertiary": "#ffffff",
          "inverse-on-surface": "#f2f0f0",
          "surface-container-lowest": "#ffffff",
          "on-tertiary-fixed": "#1c1c19",
          "inverse-surface": "#303030",
          "error-container": "#ffdad6",
          "surface-container-low": "#f5f3f3",
          "on-primary-fixed-variant": "#394760",
          "primary-fixed": "#d5e3ff",
          "on-primary-fixed": "#0c1c32",
          "tertiary-fixed-dim": "#c8c6c2",
          "tertiary-container": "#2a2a28",
          "surface-container-highest": "#e4e2e2",
          surface: "#fbf9f8",
          "on-tertiary-fixed-variant": "#474744",
          "on-tertiary-container": "#92918d",
          "on-error-container": "#93000a",
          "surface-variant": "#e4e2e2",
          primary: "#05152b",
          "surface-tint": "#505f79",
          "secondary-container": "#ffa988",
          "on-secondary": "#ffffff",
          "surface-container-high": "#eae8e7",
          "primary-fixed-dim": "#b8c7e5",
          "on-primary": "#ffffff",
          "outline-variant": "#c5c6ce",
          "on-surface": "#1b1c1c",
          "surface-bright": "#fbf9f8",
        },
        borderRadius: {
          DEFAULT: "0.125rem",
          lg: "0.25rem",
          xl: "0.5rem",
          full: "0.75rem",
        },
        spacing: {
          "margin-mobile": "20px",
          "gutter-desktop": "32px",
          "gutter-mobile": "16px",
          unit: "8px",
          "margin-desktop": "64px",
          "container-max-width": "1280px",
        },
        fontFamily: {
          "headline-md": ["Playfair Display"],
          "label-md": ["DM Sans"],
          "display-lg-mobile": ["Playfair Display"],
          "body-md": ["DM Sans"],
          "body-lg": ["DM Sans"],
          "label-sm": ["DM Sans"],
          "headline-sm": ["Playfair Display"],
          "display-lg": ["Playfair Display"],
        },
        fontSize: {
          "headline-md": [
            "32px",
            { lineHeight: "40px", fontWeight: "500" },
          ],
          "label-md": [
            "14px",
            {
              lineHeight: "20px",
              letterSpacing: "0.05em",
              fontWeight: "500",
            },
          ],
          "display-lg-mobile": [
            "32px",
            { lineHeight: "40px", fontWeight: "600" },
          ],
          "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
          "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
          "label-sm": [
            "12px",
            {
              lineHeight: "16px",
              letterSpacing: "0.08em",
              fontWeight: "700",
            },
          ],
          "headline-sm": [
            "24px",
            { lineHeight: "32px", fontWeight: "500" },
          ],
          "display-lg": [
            "48px",
            {
              lineHeight: "56px",
              letterSpacing: "-0.02em",
              fontWeight: "600",
            },
          ],
        },
      },
    },
  };