tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-background": "#0A0A0A",
                "primary-container": "#F5F5F5",
                "surface-bright": "#FFFFFF",
                "surface-tint": "#737373",
                "on-tertiary-fixed-variant": "#525252",
                "surface-container": "#F5F5F5",
                "on-surface": "#0A0A0A",
                "error": "#DC2626",
                "outline": "#737373",
                "on-tertiary-fixed": "#0A0A0A",
                "secondary-fixed": "#DCFCE7",
                "surface-container-highest": "#E5E5E5",
                "inverse-primary": "#4ADE80",
                "surface-dim": "#E5E5E5",
                "surface-container-lowest": "#FFFFFF",
                "surface-variant": "#E5E5E5",
                "on-secondary-fixed": "#052E16",
                "background": "#FFFFFF",
                "primary-fixed": "#FAFAFA",
                "on-tertiary-container": "#737373",
                "on-surface-variant": "#525252",
                "outline-variant": "#E5E5E5",
                "surface-container-low": "#FAFAFA",
                "on-tertiary": "#0A0A0A",
                "tertiary": "#0A0A0A",
                "on-primary": "#0A0A0A",
                "inverse-on-surface": "#FAFAFA",
                "secondary-container": "#86EFAC",
                "on-secondary-fixed-variant": "#166534",
                "secondary": "#16A34A",
                "error-container": "#FEE2E2",
                "surface-container-high": "#F5F5F5",
                "on-error": "#FFFFFF",
                "on-primary-fixed": "#0A0A0A",
                "on-primary-container": "#0A0A0A",
                "primary-fixed-dim": "#E5E5E5",
                "on-secondary": "#FFFFFF",
                "on-error-container": "#991B1B",
                "on-primary-fixed-variant": "#404040",
                "tertiary-container": "#F5F5F5",
                "on-secondary-container": "#14532D",
                "secondary-fixed-dim": "#86EFAC",
                "surface": "#FFFFFF",
                "inverse-surface": "#262626",
                "tertiary-fixed-dim": "#A3A3A3",
                "primary": "#FFFFFF",
                "tertiary-fixed": "#F5F5F5",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            spacing: {
                "margin-mobile": "20px",
                "container-max-width": "1280px",
                unit: "8px",
                "margin-desktop": "64px",
                "gutter-mobile": "16px",
                "gutter-desktop": "32px",
            },
            fontFamily: {
                "body-lg": ["DM Sans", "sans-serif"],
                "label-md": ["DM Sans", "sans-serif"],
                "label-sm": ["DM Sans", "sans-serif"],
                "display-lg-mobile": ["Oswald", "sans-serif"],
                "body-md": ["DM Sans", "sans-serif"],
                "headline-sm": ["Oswald", "sans-serif"],
                "display-lg": ["Oswald", "sans-serif"],
                "headline-md": ["Oswald", "sans-serif"],
            },
            fontSize: {
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
                "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
                "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
                "display-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
                "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
                "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "0.02em", fontWeight: "700" }],
                "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
            },
        },
    },
};
